### ISSUE TITLE
Enable Dependabot and fix the security issues.

### ISSUE THREAD

**Issue by hbsan** [kentaro-m/auto-assign-action#164]
Hi Could you please enable dependabot on this repository? We would like to use this action but we cannot use it since we see a critical issue when we do a scan on the repository.
Issue we see is the following;
- Babel vulnerable to arbitrary code execution when compiling specifically crafted malicious code

**Comment by kentaro-m** [comment]
@hbsan 
Thank you for your report.
I have promptly enabled Dependabot for this repository.
Additionally, I have already resolved the security issue and released [v1.2.6](https://github.com/kentaro-m/auto-assign-action/releases/tag/v1.2.6).
When you have time, please kindly check it out.
