### ISSUE TITLE
Node 16 is deprecated

### ISSUE THREAD

**Issue by bigdaz** [kentaro-m/auto-assign-action#169]
Workflows using this action receive deprecation warnings.
Please provide a new action release that runs with Node 20.

https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by jonathanstiansen** [comment]
This looks like it's been done: https://github.com/kentaro-m/auto-assign-action/blob/master/action.yml
now node 20 😄
