### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by iamsonukushwaha** [kentaro-m/auto-assign-action#41]
![image](https://user-images.githubusercontent.com/51280276/111116798-8a787d80-858c-11eb-908e-382fe08c7f64.png)

**Comment by kubode** [comment]
I have the same problem.
Is there a workflow running for the PR created by dependabot?
The permissions on the PRs created by dependabot were changed some time ago.
https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
