### ISSUE TITLE
Document where to put the list of reviewers 

### ISSUE THREAD

**Issue by vasilvestre** [kentaro-m/auto-assign-action#7]
I do not understand where I am supposed to enter the reviewer list. Could you please explain it a little bit ?

**Comment by TJFG1998** [comment]
> I do not understand where I am supposed to enter the reviewer list. Could you please explain it a little bit ?

Add to '.github/auto_assign.yml'

**Comment by vasilvestre** [comment]
Thanks a lot! :D

**Comment by brandonjmckay** [comment]
@kentaro-m So to set up this workflow we need two files?
One is `.github/worflows/whatever.yml` which holds the yaml you're showing above, and the other is `.github/auto_assign.yml` where we describe the configuration options?

Other examples from github seem like they're putting things in `.github/workflows/`, are both files supposed to not be in that folder?

**Comment by TJFG1998** [comment]
> @kentaro-m So to set up this workflow we need two files?
> One is `.github/worflows/whatever.yml` which holds the yaml you're showing above, and the other is `.github/auto_assign.yml` where we describe the configuration options?

Yes.

> Other examples from github seem like they're putting things in `.github/workflows/`, are both files supposed to not be in that folder?

@brandonjmckay 
In this case i do not think that you should put both in the ```workflow```, because that directory serves to put only the actions ```start-ups```.
